### ISSUE TITLE
Displaying math formulas is broken

### ISSUE THREAD

**Issue by DanielGibson** [dwilliamson/donw.io#16]
For example in http://donw.io/post/frustum-point-extraction/ it looks like
![brokenmath](https://user-images.githubusercontent.com/1216493/28218948-809c1850-68ba-11e7-8fd9-de5f116b9c37.png)

Similar problems in other posts with formulas

Cheers,
Daniel

**Comment by dwilliamson** [comment]
Sorry, totally missed this Issue, no idea how. Mathjax CDN went down a few months ago. Bug is fixed in this repo I just haven't uploaded it to the website yet.

**Comment by VincentTam** [comment]
You may use KaTeX instead.  It renders math much faster than MathJax.
